### ISSUE TITLE
Just saying thanks!

### ISSUE THREAD

**Issue by eboye** [sachinchoolur/jquery-to-javascript-converter#5]
I'm making this issue just to say thanks! I'm really looking forward to using this. As I often have to go to my old projects which are jQuery based and I want to replace it with vanilla just for the sake of modernization and optimization.

I see that not all the methods are replaceable, but helps a lot.

Again thanks, if I find a way to replace some other methods, I'll try to make a PR.

**Comment by sachinchoolur** [comment]
Hey @eboye,

Sure, I Will be happy to accept PR for the remaining methods
