### ISSUE TITLE
add VS code extension 

### ISSUE THREAD

**Issue by adardesign** [sachinchoolur/jquery-to-javascript-converter#7]
Thanks, looks great!
It would be nice to have a vs Code extension in addition to the CLI

**Comment by adardesign** [comment]
[maybe this should be my first extension](https://code.visualstudio.com/api/get-started/your-first-extension)

**Comment by sachinchoolur** [comment]
Sure, I'll look into this. I was planing to build eslint plugin for replace-jQuery

**Comment by coliff** [comment]
This issue has been closed and marked as completed - so is there a link to the VS Code extension available? I had a quick look on the marketplace and couldn't see it...
